# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Huyanh Hoang
emailHeader: You can reach me at
email: huyanhh at uci dot edu
description: > # this means to ignore newlines until "baseurl:"
  My name is Huyanh Hoang and I'm an aspiring entrepreneur/designer/developer/product leader.
  Right now I'm dabbling in iOS development but you'll also see me work on
  projects in web dev, software dev, or whatever other dev there is!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://huyanhhoang.me" # the base hostname & protocol for your site
twitter_username: whoyawn
github_username:  huyanhh
linkedin_username: huyanhh
youtube_username: huyanhh
medium_username: whoyawn


# Build settings
markdown: kramdown
